M48
; DRILL file {KiCad (6.0.9)} date Tue Jul  4 21:14:20 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-04T21:14:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.685Y-3.0
X1.735Y-1.1
X3.735Y-1.7
X3.735Y-2.8
T0
M30
